name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CA Certificate
        run: |
          sudo cp ./certs/certificate.pem /usr/local/share/ca-certificates/certificate.crt
          sudo update-ca-certificates

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-interaction --no-progress

      - name: Copy environment file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate app key
        run: php artisan key:generate

      - name: Execute tests
        run: php artisan test
